name: sci_computing
dependencies:
  - python
  - numpy
  - pandas
  - xarray
  - matplotlib
  - h5py
  - hvplot
  - jupyterlab
  - black
  - pint
  - sympy
  - scipy
  - iapws
  - pyvista

channels:
  - conda-forge 
